### ISSUE TITLE
Multiple repos produces yum pid lock errors

### ISSUE THREAD

**Issue by etrikp** [gocd/go-plugins#23]
Go 15.2.0-2248 and Yum plugin 2.0.0

Go is setup with 20 yum repos. When polling for changes in the repos, Go or the Yum Plugin is attempting to do so with multiple threads. The repoquery tool (and yum in general) does not support multiple threads and errors like the following are produced consistently and constantly against every repo.

    Interaction with plugin with id 'yum' implementing 'package-repository' extension failed while requesting     
    for 'latest-revision-since'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' 
    and the following response: 'Error while querying repository with path 'https://*****' and package spec
    '****'. Error Message: Existing lock /var/tmp/yum-go-_4vX3k/x86_64/7/yum.pid: another copy is running 
    as pid 33677

The result is some updated materials will not register with Go for 2 hours or more because of the lock contention.

**Comment by srinivasupadhya** [comment]
Its taken a while but we have been able to nail down the issue. As a part of yum-utils-1.1.31, locking using yum.pid file was introduced to safeguard against multiple processes editing the metadata. Since we were testing with an older version on yum-utils we were unable to replicate the issue but upon moving to yum-utils-1.1.31, we came across the issue you reported while working with multiple repos. We are happy to say that we also have a fix for the above issue.

Please download the updated plugin jar from [here](https://github.com/gocd/go-plugins/releases) (MD5 checksum: 4cd9d3b28087c55e19e11cb18c8dda29)

* Please download and place it under `/var/lib/go-server/plugins/bundled/` folder and then restart the Go server.
* Verify that the latest plugin is picked by server by navigating to `http://go-server:8153/go/admin/plugins`, the version number for the plugin should be 2.0.1.

Do let us know how this goes.

**Comment by lenucksi** [comment]
A smaller scale test of version 2.0.1 showed promising results (absence of the error). A larger scale test is to follow soon.

**Comment by sennerholm** [comment]
How did you do to make it update from multiple threads? Go version 15.1 seems to have some kind of lock for it?

**Comment by jyotisingh** [comment]
The version of yum repo with the fix comes packaged with Go 15.3.1 onwards. Closing the issue
